version: '3'
services:
  ltwcc:
    build: .
    environment:
      BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS}
      SECURITY_PROTOCOL: ${SECURITY_PROTOCOL}
      SASL_MECHANISMS: ${SASL_MECHANISMS}
      SASL_USERNAME: ${SASL_USERNAME}
      SASL_PASSWORD: ${SASL_PASSWORD}
      DEBUG: ${DEBUG}
      API_VERSION.REQUEST: ${API_VERSION_REQUEST}
      API_VERSION_FALLBACK_MS: ${API_VERSION_FALLBACK_MS}
      BROKER_VERSION_FALLBACK: ${BROKER_VERSION_FALLBACK}
      TOPIC: ${TOPIC}
      MESSAGE: ${MESSAGE}